sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite5, otherSprite2) {
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Player, function (sprite4, otherSprite) {
    sprites.destroy(VIRUS, effects.spray, 500)
})
scene.onOverlapTile(SpriteKind.Player, sprites.vehicle.roadHorizontal, function (sprite2, location2) {
    score = 3
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite8, otherSprite3) {
    sprites.destroy(VIRUS, effects.spray, 500)
    info.changeLifeBy(-3)
    game.reset()
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.purpleSwitchDown, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level8`)
})
scene.onOverlapTile(SpriteKind.Food, sprites.vehicle.roadVertical, function (sprite3, location3) {
    score = 3000
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.stairLarge, function (sprite6, location4) {
    tiles.setCurrentTilemap(tilemap`level15`)
})
let score = 0
let VIRUS: Sprite = null
let Riqueza2: Sprite = null
scene.cameraFollowSprite(Riqueza2)
tiles.setCurrentTilemap(tilemap`level8`)
Riqueza2 = sprites.create(img`
    . . . . f f f f . . . . . 
    . . f f f f f f f f . . . 
    . f f f f f f c f f f . . 
    f f f f f f c c f f f c . 
    f f f c f f f f f f f c . 
    c c c f f f e e f f c c . 
    f f f f f e e f f c c f . 
    f f f b f e e f b f f f . 
    . f 4 1 f 4 4 f 1 4 f . . 
    . f e 4 4 4 4 4 4 e f . . 
    . f f f e e e e f f f . . 
    f e f b 7 7 7 7 b f e f . 
    e 4 f 7 7 7 7 7 7 f 4 e . 
    e e f 6 6 6 6 6 6 f e e . 
    . . . f f f f f f . . . . 
    . . . f f . . f f . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Riqueza2, 100, 100)
let LIBROS = sprites.create(img`
    .......bbbbbbbbbbbbbbbbbb.......
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ...................bddddddddd...
    ..................ddddddddddddb.
    .................c1111111111111.
    ................c1bc1d1bbd1d1cb1
    ................c1bddbd111bdcdb1
    .................cc.bb1b1bbdccc.
    ....................bb1d1dddc...
    ...................dbb1d1dddbc..
    ..................cc11111111dc..
    .................c1111111111111.
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.castle.tileGrass1)
LIBROS = sprites.create(img`
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    .....................22eee2e22..................
    ...................e2e2eee2e2e2ee...............
    .................2ee2e2eee2e2e2e2e22............
    ...............6ce2e2e2eee2e2e2e22ee............
    ...............4622e2e2eee2e2e2ee222............
    ...............6c2ee2eeeee2e2e2e2e22............
    ...............6c22e2e2eee2e2e2e2222............
    ...............4622e2eec66666e2e2222............
    ...............6c22ec6666446c6cce222............
    ...............462c6c644444446cc6c22............
    ...............66b444b1111111b44444b............
    ...............66eee41e444ee414eeeee............
    ...............66edd46f4eeeee64eddde............
    ...............c6ecc46e444ee464eccde............
    ................c64446e444eff6444446............
    .................ce446f444eef64eee4c............
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    ................................................
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.vehicle.roadHorizontal)
LIBROS = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . b b b b b b . . . . . 
    . . . . b d d d d d d b . . . . 
    . . . b 1 1 1 1 1 1 1 1 b . . . 
    . . . b d 6 6 6 6 6 6 d b . . . 
    . . . b d 6 d 6 6 6 6 d b . . . 
    . . . b d 6 6 6 6 6 6 d b . . . 
    . . . b d 6 6 6 6 6 6 d b . . . 
    . . . b d c c c c c c d b . . . 
    . . . c b b b b b b b b c . . . 
    . . c 1 d d d d d d d d 1 c . . 
    . . c 1 d 1 d 1 d 1 1 1 1 c . . 
    . . c b b b b b b b b b b c . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.vehicle.roadVertical)
VIRUS = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . 8 8 8 8 . . . . 
    . . . . . . . 8 6 6 6 6 . . . . 
    . . . . . . 8 9 6 6 6 6 b 8 . . 
    . . . . . 8 9 9 7 6 6 6 9 b . . 
    . . . 8 6 6 9 9 7 7 7 7 9 9 . . 
    . . . 8 6 6 9 b b b 8 b b 9 . . 
    . . . 8 6 8 8 8 b b 8 b 8 b . . 
    . . . 8 3 3 8 8 8 8 8 8 8 8 . . 
    . . . 8 8 8 8 8 8 8 8 8 8 8 . . 
    . . . . 8 8 b c f 8 f b c f . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, sprites.castle.tileGrass1)
VIRUS = sprites.create(img`
    . . . . . . . . 
    . . . b b b b . 
    . . b 5 5 5 5 . 
    . b 5 d 3 3 d . 
    . b 5 3 5 5 1 . 
    . c 5 3 5 5 1 . 
    . c d d 1 1 d . 
    . . . . . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ............c...........
    ............cc..........
    .........cccc5555c......
    .........cc5555555c.....
    .......ccb55555f5555....
    ........b55555555555....
    ......cc555dd55513bc....
    ......cc55ddd555335c....
    .......cd5ddddd5b35c....
    ......cddddb5555cc......
    ......cdddddc555cc......
    ....cddddddd5dbbc5c.....
    ....cddddddd55dcc5......
    .....cddbbbbd555........
    ......ccbbbbd555........
    ........ccc.............
    ........................
    ........................
    `)
tiles.setCurrentTilemap(tilemap`level15`)
Riqueza2 = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Riqueza2, 100, 100)
LIBROS = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . f f f f f f . f f f f f f . 
    . f f 3 3 3 3 f f f 3 3 3 3 f f 
    . f 3 3 3 3 3 3 f 3 3 3 3 3 3 f 
    . f 3 3 3 3 3 3 3 3 1 1 1 3 3 f 
    . f 3 3 3 3 3 3 3 3 1 1 1 3 3 f 
    . f 3 3 3 3 3 b b b 1 1 1 3 3 f 
    . f 3 3 3 3 b b b b b 3 3 3 3 f 
    . f f 3 3 b b b b b b b 3 3 f f 
    . . f f 3 b b b b b b b 3 f f . 
    . . . f f b b b b b b b f f . . 
    . . . . f f b b b b b f f . . . 
    . . . . . f f b b b f f . . . . 
    . . . . . . f f b f f . . . . . 
    . . . . . . . f f f . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.castle.tilePath5)
LIBROS = sprites.create(img`
    ..........bbbbbb................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ..........bb4444b...............
    ........244444dd44..............
    .......444444444d4be............
    .....2bb4444444444bb............
    .....2b4b4444444444be...........
    .....2b4444444444444e...........
    ......2bbb4bbb44444be...........
    .......eebbbb44b4444be..........
    ..........eee22b44bbee..........
    ...............ebbbebd..........
    ....................cd1bb.......
    ......................11d.......
    ......................b1c.......
    ................................
    ...............................b
    ...............................c
    ...............................c
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.vehicle.roadTurn4)
LIBROS = sprites.create(img`
    . . . . . . . 6 . . . . . . . . 
    . . . . . . 8 6 6 . . . 6 8 . . 
    . . . e e e 8 8 6 6 . 6 7 8 . . 
    . . e 2 2 2 2 e 8 6 6 7 6 . . . 
    . e 2 2 4 4 2 7 7 7 7 7 8 6 . . 
    . e 2 4 4 2 6 7 7 7 6 7 6 8 8 . 
    e 2 4 5 2 2 6 7 7 6 2 7 7 6 . . 
    e 2 4 4 2 2 6 7 6 2 2 6 7 7 6 . 
    e 2 4 2 2 2 6 6 2 2 2 e 7 7 6 . 
    e 2 4 2 2 4 2 2 2 4 2 2 e 7 6 . 
    e 2 4 2 2 2 2 2 2 2 2 2 e c 6 . 
    e 2 2 2 2 2 2 2 4 e 2 e e c . . 
    e e 2 e 2 2 4 2 2 e e e c . . . 
    e e e e 2 e 2 2 e e e c . . . . 
    e e e 2 e e c e c c c . . . . . 
    . c c c c c c c . . . . . . . . 
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.builtin.forestTiles0)
VIRUS = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . c c b b b b . . . . . 
    . . . . c b 4 4 4 4 b b . . . . 
    . . . e 4 4 4 4 4 4 5 4 e . . . 
    . . e b 4 4 4 4 4 4 4 4 4 . . . 
    . . . e b 4 4 4 5 4 4 b e . . . 
    . . 8 7 e b 4 4 4 4 b e 6 . . . 
    . . e 6 6 2 2 2 2 2 2 6 c . . . 
    . . e b e 8 c 8 8 c c e b . . . 
    . . . e e b 4 4 4 4 4 e e . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, sprites.vehicle.roadHorizontal)
VIRUS = sprites.create(img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    .............cccc666............
    ............c444444466..........
    ...........c444444b4446.........
    ..........cb4bb4445b444b........
    ........e6bb44444b445b4446......
    ........ebb544444bb4b4bb4e......
    .......e6b4b4444444444b5b4......
    ......eb6b444b444444444444......
    ......fb66b444444444b44444......
    .......fb666b444444444444b......
    .......efb666b44444444444f......
    .......86cbb66bb4444444bc6......
    ......f8662222222222222768......
    ......fef666766677776777ff......
    ......fbf8776867777677ffff......
    ......f6bffefeeeeeeefeeeeb......
    .......c6dddefffeeeeffddb6......
    .......fcb4dddddddddddb44e......
    .........ffbb4444444444ee.......
    ...........febbb44444ee.........
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, sprites.castle.tilePath5)
tiles.setCurrentTilemap(tilemap`level6`)
Riqueza2 = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Riqueza2, 100, 100)
LIBROS = sprites.create(img`
    .cccccccccccccccccccccc.
    cbddddddddddddddddddddbc
    cddddddddddddddddddddddc
    cddddddddddddddddddddddc
    cddddddddddddddddddddddc
    cddddddddddddddddddddddc
    cddddddddddddddddddddddc
    cbddddddddddddddddddddbc
    ccbbbbbbbbbbbbbbbbbbbbcc
    ccffffffffffffffffffffcc
    cbcc33c6c44c3c7c66c3ccbc
    cbcc33c6c44c3c7c66c3ccbc
    fbcc33c6c44ccc7c66c3ccbf
    fdccccccccccccccccccccdf
    fdcbbddddddddddddddbbcdf
    fdffffffffffffffffffffdf
    fdccc6c33c4c6c44c3c7ccdf
    fdccc6c33c4c6c44c3c7ccdf
    fdccc6c33ccc6c44ccc7ccdf
    fdccccccccccccccccccccdf
    fdcbbddddddddddddddbbcdf
    fdcbbddddddddddddddbbcdf
    fdffffffffffffffffffffdf
    ffffffffffffffffffffffff
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.vehicle.roadHorizontal)
LIBROS = sprites.create(img`
    .cccccccccccccc.
    cbddddddddddddbc
    cddddddddddddddc
    cddddddddddddddc
    cddddddddddddddc
    cddddddddddddddc
    cddddddddddddddc
    cbddddddddddddbc
    ccbbbbbbbbbbbbcc
    ccffffffffffffcc
    cbc44c7c66c3ccbc
    cbc44c7c66c3ccbc
    fbc44c7c66c3ccbf
    fdccccccccccccdf
    fdcbbddddddbbcdf
    fdffffffffffffdf
    fdcc4c44c3c7ccdf
    fdcc4c44c3c7ccdf
    fdcccc44ccc7ccdf
    fdccccccccccccdf
    fdcbbddddddbbcdf
    fdcbbddddddbbcdf
    fdffffffffffffdf
    ffffffffffffffff
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.vehicle.roadHorizontal)
LIBROS = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . c c c c c c c c c c c c . . . 
    c 1 1 1 1 1 1 1 1 1 1 1 1 c . . 
    c d d d d d d d d d d d d c . . 
    c d c c c c c c c c c c d c . . 
    c d b d b b b b b b b b d c . . 
    c d b b b b b b b b b b d c . . 
    c d b b b b b b b b b b d c . . 
    c d b b b b b b b b b b d c . . 
    c 1 b b b b b b b b b b 1 c . . 
    c 1 1 d 1 1 d 1 1 d 1 1 1 c . . 
    c 1 d d d d d d d d d d 1 c . . 
    c 1 d 1 1 d 1 1 d 1 1 d 1 c . . 
    c b b b b b b b b b b b b c . . 
    c c c c c c c c c c c c c c . . 
    `, SpriteKind.Food)
tiles.placeOnRandomTile(LIBROS, sprites.builtin.forestTiles0)
VIRUS = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........ec.........
    ........eeee........
    .......ee4eee.......
    ......ee4eeeee......
    .....ee4eeeeeee.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, sprites.builtin.forestTiles0)
VIRUS = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........ec.........
    ........eeee........
    .......ee4eee.......
    ......ee4eeeee......
    .....ee4eeeeeee.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
tiles.placeOnRandomTile(VIRUS, img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . b b b b b . . . . . . 
    . . . . . 1 d d d d b . . . . . 
    . . . . b b c c c c d . . . . . 
    . . . . b c 6 6 6 6 d . . . . . 
    . . . . b c 6 6 6 6 d . . . . . 
    . . . . b c 6 6 6 6 d . . . . . 
    . . . . b c c c c c d . . . . . 
    . . . c b c c c c c c c . . . . 
    . . . c 1 d d d d d d c . . . . 
    . . . c b b b b b b b c . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `)
info.changeScoreBy(1)
sprites.destroy(Riqueza2, effects.spray, 1000)
